### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by avivajpeyi** [alexa-samples/skill-sample-python-quiz-game#19]
Hi, was wondering if Amazon might be able to provide some examples of testing in python with `ask_sdk_core`? 
I want to test out some successful dialogue scenario between a user and Alexa. 

More specifically, I would like to see an example of how I can pass a test user utterances to `skill-sample-python-quiz-game/lambda/py/lambda_function.py`, and see which intent handler is fired, check that the dialogue that is returned is what I expect, etc.

**Comment by aszk** [comment]
You can see what you sent to Alexa, and what you received from Alexa using interceptors. https://developer.amazon.com/blogs/alexa/post/75ee61df-8365-44bb-b28f-e708000891ad/how-to-use-interceptors-to-simplify-handler-code-and-cache-product-and-purchase-information-in-monetized-alexa-skills
