### ISSUE TITLE
The repository can't be imported into Alexa as a Skill

### ISSUE THREAD

**Issue by ivanoterouvigo** [alexa-samples/skill-sample-python-quiz-game#23]
Hello everyone,

I've just imported the this example of skill in Alexa developer as you can see in the screen but with no sucess.

![Alexa-implementación-012](https://github.com/alexa-samples/skill-sample-python-quiz-game/assets/11814769/a2cb1bc0-fce1-44ac-b3b6-4522dfd8ff91)

Here you are the error reported.

![Alexa-implementación-013](https://github.com/alexa-samples/skill-sample-python-quiz-game/assets/11814769/78f7563d-a03c-479f-8fac-1276c407f827)

Thanks in advance

**Comment by aszk** [comment]
Thank you for the report. I am sending a PR for this. For the future reference, repositories need to follow the specific structure to import to Alexa-hosted environment from GitHub. https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-git-import.html

**Comment by aszk** [comment]
The PR has been merged.
